import { COMMONLY_FORGOTTEN_ITEMS } from './commonly-forgotten-items';
import { formatLabel } from './format-labels';

export type EstimateForExport = {
  projectType: string;
  areaSqFt?: number;
  quantity?: number;
  costLow: number;
  costMid: number;
  costHigh: number;
  details: Record<string, string | number>;
  materials?: {
    name: string;
    quantity: number;
    unit: string;
    costLow: number;
    costMid: number;
    costHigh: number;
  }[];
};

export function exportEstimateToCSV(input: string, est: EstimateForExport): void {
  const rows: string[][] = [];
  const escape = (v: string | number) => `"${String(v).replace(/"/g, '""')}"`;

  rows.push(['Pink Print — Cost Estimate']);
  rows.push(['Project', input]);
  rows.push(['Project Type', est.projectType]);
  rows.push([]);
  rows.push(['Cost Estimate', 'Low', 'Mid', 'High']);
  rows.push(['', `$${est.costLow.toLocaleString()}`, `$${est.costMid.toLocaleString()}`, `$${est.costHigh.toLocaleString()}`]);
  rows.push([]);
  rows.push(['Project Specs', 'Color']);
  for (const [key, value] of Object.entries(est.details)) {
    rows.push([formatLabel(key), String(value)]);
  }
  if (est.materials && est.materials.length > 0) {
    rows.push([]);
    rows.push(['Materials', 'Qty', 'Unit', 'Cost Low', 'Cost High']);
    for (const m of est.materials) {
      rows.push([m.name, String(m.quantity), m.unit, `$${m.costLow.toLocaleString()}`, `$${m.costHigh.toLocaleString()}`]);
    }
  }
  rows.push([]);
  rows.push(["Don't Forget Checklist"]);
  const dontForgetItems =
    COMMONLY_FORGOTTEN_ITEMS[est.projectType?.toLowerCase() || 'painting'] ?? COMMONLY_FORGOTTEN_ITEMS.painting;
  for (const item of dontForgetItems) {
    rows.push([item, '']);
  }
  rows.push([]);
  rows.push(['Generated by Pink Print', new Date().toLocaleDateString()]);

  const csv = rows.map((r) => r.map(escape).join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `pink-print-estimate-${Date.now()}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
